### ISSUE TITLE
How to track the slide deck

### ISSUE THREAD

**Issue by shawalli** [booz-allen-hamilton/BasicProtocolReverseEngineeringTalk#1]
Any thoughts on how to save the slide deck as well? Since it's binary, won't every commit of the slide deck store off a whole new version of the slide deck? I'm not as familiar with git as svn, but in svn, this is what would happen. I think git only tracks diffs in directories, as opposed to files, so each commit would be seen as a whole file's worth of diffs.

**Comment by wjilani** [comment]
Yeah, so I don't think Git would be the best place for the deck since it's not meant for presentations and like you said, the repo will get huge due to how it stores things., but I'm not sure how else to do it. Since it's just 1 deck and we don't expect code check-ins (this whole repo should stay static), I suppose it's the best we can do to distribute the slides. I'm good with it.
